services:
  accounts:
    image: "hiendat04/accounts:v1"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-banking-system
  loans:
    image: "hiendat04/loans:v1"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-banking-system
  cards:
    image: "hiendat04/cards:v1"
    container_name: "cards-ms"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ms-banking-system

networks:
  ms-banking-system:
    driver: bridge